[build-system]
requires = [
    "whey"
]
build-backend = "whey"

[project]
name = "wrayco"
version = "0.0.1"
dependencies = ["youtube-dl", "tornado"]

[project.scripts]
wrayco = "wrayco:main"

[tool.whey]
additional-files = [
    "include wrayco/templates/*",
    "include wrayco/static/*",
]
